//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServicePlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerServicePlan()
        {
            this.HistoryCustomerServicePlans = new HashSet<HistoryCustomerServicePlan>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ActiveDate { get; set; }
        public Nullable<System.DateTime> ExtendDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string code { get; set; }
        public int ServicePlanID { get; set; }
        public int ProvinceID { get; set; }
        public int DistrictID { get; set; }
        public int VillageID { get; set; }
        public string Address { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual ServicePlan ServicePlan { get; set; }
        public virtual Village Village { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryCustomerServicePlan> HistoryCustomerServicePlans { get; set; }
    }
}
