//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int ServicePlanID { get; set; }
        public double TotalPrice { get; set; }
        public double Discount { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ServicePlan ServicePlan { get; set; }
    }
}
